/*
  Spis wszystkich ikon Material Symbols używanych w serwisie.

  Po tym spisie `npm run ikony` (scripts/pobierz-ikony.mjs) przycina pismo
  ikon: zamiast pełnych 5,3 MB (wszystkie ~3800 ikon we wszystkich odmianach)
  w repo leży ~100 KB z samymi naszymi ikonami. Dlatego każda ikona rysowana
  na stronie musi tu stać - inaczej zamiast rysunku wyświetli się jej nazwa
  zapisana słowem.

  Pilnuje tego kompilator: typ IconName powstaje z tej listy i <Icon> nie
  przyjmie nazwy spoza niej. Nową ikonę z fonts.google.com/icons dopisz
  poniżej (alfabetycznie) i puść `npm run ikony`, żeby dojechała do pliku
  fontu.
*/

export const ICON_NAMES = [
  "abc",
  "account_circle",
  "account_tree",
  "add",
  "add_box",
  "add_photo_alternate",
  "arrow_back",
  "arrow_outward",
  "arrow_selector_tool",
  "article",
  "balance",
  "biotech",
  "brightness_auto",
  "brush",
  "calculate",
  "calendar_month",
  "change_history",
  "check",
  "checklist",
  "chevron_left",
  "chevron_right",
  "circle",
  "close",
  "cloud",
  "code",
  "create_new_folder",
  "crop_square",
  "dark_mode",
  "data_object",
  "delete",
  "delete_forever",
  "delete_sweep",
  "diamond",
  "download",
  "draft",
  "draw",
  "drive_file_move",
  "edit",
  "edit_note",
  "expand_more",
  "explore",
  "favorite",
  "fit_screen",
  "flag",
  "folder",
  "folder_off",
  "format_align_center",
  "format_align_left",
  "format_align_right",
  "format_bold",
  "format_color_fill",
  "format_color_reset",
  "format_color_text",
  "format_h1",
  "format_h2",
  "format_h3",
  "format_italic",
  "format_list_bulleted",
  "format_list_numbered",
  "format_quote",
  "format_size",
  "format_strikethrough",
  "format_underlined",
  "functions",
  "genetics",
  "gesture",
  "grid_on",
  "hide_image",
  "home",
  "horizontal_rule",
  "hourglass_top",
  "image",
  "inbox",
  "ink_eraser",
  "ink_highlighter",
  "install_mobile",
  "key",
  "label",
  "landscape",
  "light_mode",
  "lightbulb",
  "linear_scale",
  "link",
  "local_cafe",
  "local_library",
  "map",
  "menu_book",
  "more_vert",
  "music_note",
  "note",
  "note_add",
  "opacity",
  "open_in_new",
  "palette",
  "park",
  "photo_camera",
  "post_add",
  "public",
  "publish",
  "redo",
  "restore",
  "restore_from_trash",
  "rocket_launch",
  "rounded_corner",
  "save",
  "schedule",
  "schema",
  "science",
  "search_off",
  "select_all",
  "settings",
  "shapes",
  "shield",
  "shield_person",
  "sports_soccer",
  "square_foot",
  "star",
  "stylus",
  "subdirectory_arrow_right",
  "table_chart",
  "text_decrease",
  "text_format",
  "text_increase",
  "theater_comedy",
  "undo",
  "unfold_less",
  "unfold_more",
  "upload",
  "visibility",
  "warning",
  "workspace_premium",
  "zoom_in",
  "zoom_out",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
